SSDM-13052 : Archiving Investigation and Follow Up - obtain a new IHierarchicalContent instance for every sanity check attempt as after a failure the content node may be in an inconsistent state leading to exceptions like:
java.lang.IllegalArgumentException: Resource '20220825104631407-1883' does not exist.
        at ch.systemsx.cisd.openbis.dss.generic.shared.content.PathInfoProviderBasedHierarchicalContent.getNode(PathInfoProviderBasedHierarchicalContent.java:84)
        at ch.systemsx.cisd.openbis.common.io.hierarchical_content.FilteredHierarchicalContent.getNode(FilteredHierarchicalContent.java:53)
        at ch.systemsx.cisd.openbis.dss.generic.server.plugins.standard.archiver.MultiDataSetArchivingUtils.sanityCheck(MultiDataSetArchivingUtils.java:71)